include: package:workiva_analysis_options/v2.yaml
# This rule isn't currently enabled becaus there are valid uses for using 'as', such as
# verifying that an object is a specific mixin.
#    - avoid_as

# These rules were found to be unenforceable as they would require breaking changes or
# were too noisy.
#    - implementation_imports
#    - non_constant_identifier_names
#    - one_member_abstracts
